-- INSERT INTO `pokemon` (`id`, `name`, `type`, `attack`, `hp`, `speed`) VALUES ('1', 'Pikachu', 'Electric', '10', '10', '9');
-- INSERT INTO `pokemon` (`id`, `name`, `type`, `attack`, `hp`, `speed`) VALUES ('2', 'Squirtle', 'Water', '8', '10', '8');
-- INSERT INTO `pokemon` (`id`, `name`, `type`, `attack`, `hp`, `speed`) VALUES ('3', 'Charmander', 'Fire', '9', '10', '7');