@baseUrl = http://localhost:8080

### create one employee
POST {{baseUrl}}/api/employee HTTP/1.1
content-type: application/json

{
    "firstName": "Pista",
    "lastName": "Ruszki",
    "email": "rp@email.org"
}

# expect return code 201 (Created)
# expect in response body the same employee with a unique ID
# {"id":1, "lastName":"Ruszki", "firstName":"Pista", "email":"rp@email.org" }
# expect posted employee to appear in MariaDB database ems / table employees
# in a terminal:
# $ mariadb -u root -p
# Enter password: 
# Welcome to the MariaDB monitor....
#
# MariaDB [(none)]> select * from ems.employees;
# +----+--------------+------------+-----------+
# | id | email        | first_name | last_name |
# +----+--------------+------------+-----------+
# |> 1 | rp@email.org | Pista      | Ruszki   <|
# +----+--------------+------------+-----------+
# 1 row in set (0.000 sec)


### create another employee
POST {{baseUrl}}/api/employee HTTP/1.1
content-type: application/json

{ "firstName": "John", "lastName": "Doe", "email": "jdoe@email.org" }

# expect return code 201 (Created)
# expect in response body the same employee with a unique ID
# {"id":2, "lastName":"Doe", "firstName":"John", "email":"jdoe@email.org" }
# expect posted employee to appear in MariaDB database ems / table employees
# MariaDB [(none)]> select * from ems.employees;
# +----+----------------+------------+-----------+
# | id | email          | first_name | last_name |
# +----+----------------+------------+-----------+
# |  1 | rp@email.org   | Pista      | Ruszki    |
# |> 2 | jdoe@email.org | John       | Doe      <|
# +----+----------------+------------+-----------+


### read all employees
GET {{baseUrl}}/api/employee HTTP/1.1

# expect in response body both employees
# [ 
#   {"id":1, "lastName":"Ruszki", "firstName":"Pista", "email":"rp@email.org" }
#   {"id":2, "lastName":"Doe",    "firstName":"John",  "email":"jdoe@email.org" }
# ]


### read one employee by ID
GET {{baseUrl}}/api/employee/2 HTTP/1.1

# expect in response body the employee with ID=2
#   {"id":2, "lastName":"Doe", "firstName":"John", "email":"jdoe@email.org" }


### updete one employee by ID
PUT {{baseUrl}}/api/employee/2 HTTP/1.1

{ "firstName": "John", "lastName": "Doe", "email": "johndoe@email.org" }

# expect in response body the employee with ID=2
#   {"id":2, "lastName":"Doe", "firstName":"John", "email":"jdoe@email.org" }
